### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by yihui** [rbind/r-podcast#39]
I can't access https://www.r-podcast.org now, and discovered this problem when trying to [get a screenshot of this site](https://github.com/rstudio/blogdown/blob/62469ad3dc804ebc3abebbd21c85a05fd6bffe59/vignettes/articles/examples.Rmd#L20) on Github Action in blogdown.

**Comment by rpodcast** [comment]
I'm so sorry I missed this! I had a problem with the domain registrar but I believe I fixed it towards the end of last year. Hopefully you are able to access the site again too.

**Comment by yihui** [comment]
No worries! I can confirm that I can access it now.
